const langContent = {
  'en': {
    'hero-title': 'Marina Zhukovich',
    'position': 'Frontend developer',
    'location': 'Belarus, Minsk',
    'contacts': 'Contacts:',
    'experience': 'Experience:',
    'skills': 'Skills:',
    'projects': 'Projects:',
    'languages': 'Languages:',
    'education': 'Education:',
    'lang-eng': 'English: B1',
    'lang-ru': 'Russian: native',
    'lang-bel': 'Belarusian: native',
    'exp-mtc': '– 03.2022 – present The branch of BSEU" Minsk Trade College".',
    'exp-sc': '06.2008 – 10.2021 UE “Components and systems” – accountant.',
    'responsibilities': 'Responsibilities:',
    'responsibilities-item-1': 'creation site on WordPress, optimization of layout and styles;',
    'responsibilities-item-2': 'development of additional functionality in JS, Node.JS, MySQL;',
    'responsibilities-item-3': 'site administration.',
    'tech-stack': 'Tech stack:',
    'speciality': 'Software engineer',
    'online-store': 'Online store',
    'store-task-1': 'layout of all components + adaptive, work with sliders (Swiper Slider);',
    'store-task-2': 'get and post requests (subscribing to the newsletter, receiving goods, transferring order data to the server, sending feedback);',
    'store-task-3': 'rendering of received data;',
    'store-task-4': 'form validation;',
    'store-task-5': 'filtering products by category;',
    'store-task-6': 'work with the shopping cart (adding goods, changing the quantity, calculating the cost, processing delivery).',
    'todo-list': 'TODO list',
    'todo-task-1': 'layout of all components;',
    'todo-task-2': 'adding, deleting tasks;',
    'todo-task-3': 'sorting tasks by categories;',
    'todo-task-4': 'the ability to make the task important;',
    'todo-task-5': 'word search.',
    'college': 'Official college website',
    'college-task-1': 'creation and administration of the site;',
    'college-task-2': 'hosting, connection of an SSL certificate;',
    'college-task-3': 'optimization of layout, styles;',
    'college-task-4': 'creating an API based on Node.JS;',
    'college-task-5': 'compiling a tree of PDF files with the ability to view and download;',
    'college-task-6': 'connecting Telegram bot and sending notifications to the Telegram channel when certain events occur;',
    'college-task-7': 'differentiation of access to content according to user roles.',
    'js-task-1': 'layout + adaptive;',
    'js-task-2': 'functionality in JS (working with API, sliders, sorting, validating forms and fields, changing the color theme, choosing a language, authorization, separation of rights for administrator and user etc.).',
    'portfolio-website': 'Portfolio website',
    'movie-gallery': 'Movie gallery',
    'animal-shelter': 'Animal shelter website',
    'cafe-website': 'Cafe website',
    'education-inst': 'Private Institute of Management and Business',
    'education-inst-spec': 'Economist-manager',
    'education-college': 'The branch of BSEU "Minsk Trade College"',
    'education-college-spec': 'Accounting and audit'
  },
  'ru': {
    'hero-title': 'Марина Жукович',
    'position': 'Фронтенд-разработчик',
    'location': 'Беларусь, Минск',
    'contacts': 'Контакты:',
    'experience': 'Опыт работы:',
    'skills': 'Навыки:',
    'projects': 'Проекты:',
    'languages': 'Языки:',
    'education': 'Образование:',
    'lang-eng': 'Английский: B1',
    'lang-ru': 'Русский: родной',
    'lang-bel': 'Белорусский: родной',
    'exp-mtc': '03.2022 – настоящее время – Филиал БГЭУ «Минский торговый колледж».',
    'exp-sc': '06.2008 – 10.2021 УП «Компоненты и системы» – бухгалтер.',
    'responsibilities': 'Обязанности:',
    'responsibilities-item-1': 'создание сайта на WordPress, доработка верстки и стилей; ',
    'responsibilities-item-2': 'разработка дополнительного функционала на JS, Node.JS, MySQL;',
    'responsibilities-item-3': 'администрирование сайта.',
    'tech-stack': 'Технологии:',
    'speciality': 'Инженер-программист – ',
    'online-store': 'Интернет-магазин',
    'store-task-1': 'верстка всех компонентов по макету + адаптив, работа со слайдерами (Swiper Slider);',
    'store-task-2': 'get и post запросы (подписка на рассылку, получение товаров, передача данных о заказе на сервер, отправка отзывов);',
    'store-task-3': 'рендеринг (отрисовка) полученных данных;',
    'store-task-4': 'валидация форм;',
    'store-task-5': 'фильтрация товаров по категориям;',
    'store-task-6': 'работа с корзиной (добавление товара, изменение кол-ва, расчет стоимости, оформление доставки).',
    'todo-list': 'Список дел',
    'todo-task-1': 'верстка всех компонентов;',
    'todo-task-2': 'добавление, удаление задач;',
    'todo-task-3': 'сортировка задач по категориям;',
    'todo-task-4': 'возможность сделать задачу важной;',
    'todo-task-5': 'поиск по задачам.',
    'college': 'Официальный сайт колледжа',
    'college-task-1': 'создание и администрирование сайта;',
    'college-task-2': 'размещение на хостинг, подключение SSL-сертификата;',
    'college-task-3': 'оптимизация верстки, стилей;',
    'college-task-4': 'создание API на базе Node.JS;',
    'college-task-5': 'составление дерева PDF файлов с возможностью просмотра и скачивания;',
    'college-task-6': 'подключение Telegram bot и отправка уведомлений в Telegram канал при совершении определенных событий;',
    'college-task-7': 'разграничение доступа к контенту согласно ролям пользователей.',
    'js-task-1': 'верстка + адаптив;',
    'js-task-2': 'функционал на JS (работа с API, слайдерами, сортировка, валидация форм и полей, смена цветовой темы, выбор языка,  авторизация, разделение прав для администратора и пользователя и др).',
    'portfolio-website': 'Сайт портфолио',
    'movie-gallery': 'Галерея фильмов',
    'animal-shelter': 'Сайт помощи животным',
    'cafe-website': 'Сайт кафе',
    'education-inst': 'Институт управления и предпринимательства',
    'education-inst-spec': 'экономист-менеджер',
    'education-college': 'Филиал БГЭУ «Минский торговый колледж» ',
    'education-college-spec': 'бухгалтер',
  }

}

export default langContent;